# Seeds file

Task.create(name: "Chompies", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Chompy_bird.png?6d30f")
Task.create(name: "Castle Wars", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Decorative_armour_%28gold_platebody%29_detail.png?716ba")
Task.create(name: "Trouble Brewing", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Gilded_smile_flag_detail.png?390a5")
Task.create(name: "Shades of Mor'ton locks", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Bronze_locks_detail.png?6533f")
Task.create(name: "easy clue scrolls", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/H.A.M._Member_%28male%29_chathead.png?7bb02")
Task.create(name: "Lesser Demon champ scroll", single_clog: true, image_url: "https://oldschool.runescape.wiki/images/Lesser_demon_champion_scroll_detail.png?bb4be")
Task.create(name: "Aerial Fishing", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Golden_tench_detail.png?27700")
Task.create(name: "infernal mages", single_clog: true, image_url: "https://oldschool.runescape.wiki/images/Infernal_Mage.png?f3e68")
Task.create(name: "Royal Titans", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Royal_Titans_logo.png?dd64c")
Task.create(name: "Mastering Mixology", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Mox_paste_detail.png?fa107")
Task.create(name: "Guardians of the Rift", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Rift_guardian_%28follower%2C_fire%29.png?725c4")
Task.create(name: "Mage Training Arena", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Maze_Guardian.png?47cd7")
Task.create(name: "Camdozaal", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Imcando_hammer_detail.png?78a88")
Task.create(name: "earthbound tecpotl", single_clog: true, image_url: "https://oldschool.runescape.wiki/images/Earthbound_tecpatl_detail.png?e90ae")
Task.create(name: "Charting", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/Captain%27s_log_detail.png?ff91d")

# Task.create(name: "Hobgoblin champ scroll", single_clog: true, image_url: "https://oldschool.runescape.wiki/images/Hobgoblin_champion_scroll_detail.png?37397")
# Task.create(name: "Vale Totems", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/thumb/Vale_offerings_detail.png/130px-Vale_offerings_detail.png?fc9df")
