# Seeds file

Task.create(name: "chompies", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=46099")
Task.create(name: "Castle Wars", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=92884")
Task.create(name: "Trouble Brewing", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=201145")
Task.create(name: "Shades of Mor'ton locks", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=299290")
Task.create(name: "easy clue scrolls (pickpocketing H.A.M. members)", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=114821")
Task.create(name: "cannoning Hobgoblins for champion scroll", single_clog: true, image_url: "https://oldschool.runescape.wiki/index.php?curid=201966")
Task.create(name: "cannoning Lesser Demons for champion scroll", single_clog: true, image_url: "https://oldschool.runescape.wiki/w/Lesser_demon_champion_scroll")
Task.create(name: "Aerial Fishing", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=204311")
Task.create(name: "infernal mages", single_clog: true, image_url: "https://oldschool.runescape.wiki/index.php?curid=15715")
Task.create(name: "Royal Titans", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=566330")
Task.create(name: "Mastering Mixology", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=537693")
Task.create(name: "Vale Totems", single_clog: false, image_url: "https://oldschool.runescape.wiki/images/thumb/Vale_offerings_detail.png/130px-Vale_offerings_detail.png?fc9df")
Task.create(name: "Guardians of the Rift", single_clog: false)
Task.create(name: "Mage Training Arena", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=216676")
Task.create(name: "Camdozaal", single_clog: false, image_url: "https://oldschool.runescape.wiki/index.php?curid=308704")
Task.create(name: "earthbound tecpotl", single_clog: true, image_url: "https://oldschool.runescape.wiki/index.php?curid=594096")
